export const TODO_KANBAN_ACTION = {
    ADD_TODO: 'ADD_TODO',
    UPDATE_TODO: 'UPDATE_TODO',
    DELETE_TODO: 'DELETE_TODO',
    SEARCH_TODO: 'SEARCH_TODO',
    DRAG_END_TODO: 'DRAG_END_TODO',
} as const;
